sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static file
deploy:
  provider: pages
  skip-cleanup: true
  github-token: fdd93ff02f50387d23aba5e16f442e17e0e367f6
  keep-history: true
  on:
    branch: master
  local-dir: public
